application: danugroup
version: 2
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: django
  version: "1.5"
- name: PIL
  version: "1.1.7"
- name: MySQLdb
  version: "latest"
- name: ssl
  version: latest

builtins:
- django_wsgi: on

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'

handlers:
- url: /jsghg
  static_dir: static/jsghg/

- url: /cssghg
  static_dir: static/cssghg/

- url: /emissions
  static_dir: static/emissions/

- url: /geo
  static_dir: static/geo/

- url: /csssocial
  static_dir: static/csssocial/

- url: /jssocial
  static_dir: static/jssocial/

- url: /images
  static_dir: static/images/

- url: /static
  static_dir: static
